{"name": "Verify error display if try save appointment without data", "status": "passed", "description": "Проверка отображения ошибки при попытке сохранить обращение без заполненных данных.", "steps": [{"name": "Выделяется заявка номер: 6", "status": "passed", "parameters": [{"name": "number", "value": "6"}], "start": 1579866331110, "stop": 1579866332379}, {"name": "Нажать на кнопку сохранить заявку", "status": "passed", "start": 1579866332379, "stop": 1579866332844}, {"name": "Ошибка сохранения отображается", "status": "passed", "start": 1579866332844, "stop": 1579866332959}], "attachments": [{"name": "log", "source": "00f2c1cd-2bfd-4256-b93a-3897e4899c0b-attachment.txt", "type": "text/plain"}], "start": 1579866329481, "stop": 1579866332959, "uuid": "ad59309b-6048-4df3-9920-ac74c304669c", "historyId": "98fd29f41e09050c3aea8c5126d36298", "testCaseId": "a31d7eba551ff8eb852ec8892552bb44", "fullName": "tests.test_do.TestUI#test_error_save_appointment_without_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_do"}, {"name": "subSuite", "value": "TestUI"}, {"name": "host", "value": "iMac-1.local"}, {"name": "thread", "value": "27895-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_do"}]}